---
- name: Deploy website
  hosts: all
  become: true

  tasks:
    - name: Copy index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Restart Apache
      service:
        name: httpd
        state: restarted